name: cryptop
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

  # Networking
  http: ^0.13.6

  # State Management
  get: ^4.6.5

  # Others
  sizer: ^2.0.15
  flutter_typeahead: ^4.3.8
  intl: ^0.18.1
  shimmer: ^2.0.0
  flutter_native_splash: ^2.2.19


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/bg.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon.png

flutter:
  uses-material-design: true
